apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - source.yaml
  - release.yaml
  - sealed-secret-postgres.yaml
  - sealed-secret-mastodon-server.yaml
configMapGenerator:
  - name: mastodon-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
