apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mastodon
  namespace: default
spec:
  interval: 5m
  url: https://github.com/mastodon/mastodon
  ref:
    tag: v4.0.2
  ignore: |
    exclude all
    !/chart/
